# service配置
server:
  port: 8090
  context-path: /




# myBatis配置
mybatis:
  mapper-locations: classpath:com/ice/agile/anagile/mapper/**/*Mapper.xml
  type-aliases-package: com.ice.agile.anagile.entity
  config-location: classpath:mybatis-config.xml



# pagehelper分页插件 配置失效在configuration文件夹MybatisConfig类中配置
#pagehelper:
#  helper-dialect: mysql
#  params: count=countSql
#  support-methods-arguments: true
#  reasonable: true



# 数据源配置
spring:
  datasource:
    # JDBC配置
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/agile?useUnicode=true&useSSL=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      name: test
      initial-size: 5 #连接池的补充设置，应用到上面所有数据源中
      min-idle: 5     #最小链接数
      max-active: 20  #最大连接数
      max-wait: 60000 #配置获取链接等待超时的时间 单位毫秒
      time-between-eviction-runs-millis: 60000  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000    #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true    #打开PSCache，并且指定每个连接上PSCache的大小
      max-open-prepared-statements: 20
      ## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      filters: stat,wall,log4j     #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        login-username: admin
        login-password: admin
        url-pattern: /druid/*
        reset-enable: false
        allow: 127.0.0.1      #IP白名单
        deny: 192.168.0.38j   #IP黑名单 两者相同时，allow优先

      #spring 监控配置 c.i.a.s.mapper* 必须配置spring.aop.proxy-target-class=true
      #aop-patterns:

  #事务代理模式有两种:java自带的动态代理模式和cglib代理模式(true)
  aop:
    proxy-target-class: true




  #时间显示格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT


#    # 连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    # 配置获取链接等待超时的时间 单位毫秒
#    maxWait: 60000
#    #  配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    spring.datasource.filters: stat,wall,logback
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

  # 是否在控制台打印sql语句)针对jpa
  #jpa:
    #show-sql: true
    #hibernate.format_sql=true




# 配置控制台打印sql 针对mybatis
logging:
  level:
    com.ice.agile: debug





#######Redis配置########
#spring.redis.host=59.49.99.226
#spring.redis.password=
#spring.redis.port=6379
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=1000


